# Generated by Django 2.2.3 on 2020-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_url', models.URLField(unique=True)),
                ('currency_key', models.CharField(max_length=10)),
                ('rate_key', models.CharField(max_length=10)),
            ],
        ),
    ]
